## Introduction to Tensors

In [1]:
import tensorflow as tf

In [2]:
# Create tensors with tf.constant()
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check dimentions
scaler.ndim

0

In [4]:
# Create vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
vector.ndim

1

In [6]:
# Create a matrix more than 1 dimention
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix 
another_matrix = tf.constant([[10.,7,],
                             [3.,2.],
                             [8.,9.]], dtype=tf.float16)

In [9]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
# Create a tensor
tensor = tf.constant([
    [[1,2,3],
    [4,5,6]],
    [[7,9,8],
    [10,11,12]],
    [[13,14,15],
    [16,17,18]]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  9,  8],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [12]:
tensor.ndim

3

## List

* Scalar: a single number
* Vector : a number with direction
* Matrix : a 2-dimentional array of numbers
* Tensor : an n-dimentional array of numbers (n can be any number like 0,1,2)

## Create tensor using tf.Variable

In [13]:
# Create same tensor with tf.Variable() as above
changeble_tensor = tf.Variable([10,7])
unchangeble_tensor = tf.constant([10,7])

changeble_tensor, unchangeble_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [14]:
changeble_tensor[0] = 7
changeble_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [15]:
# Try .assign()
changeble_tensor[0].assign(7)
changeble_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [16]:
unchangeble_tensor[0] = 7

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [17]:
unchangeble_tensor[0].assign(6)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## Creating random tensors

In [18]:
# Create two random tensor
random_1 = tf.random.Generator.from_seed(42) # same sequence of random numbers every time you run your code,
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [19]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [20]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

## Shuffle the order of elements in a tensor

In [21]:
# Shuffle a tensor (Shuffle your data)
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])

shuffled_tensor = tf.random.shuffle(not_shuffled)

shuffled_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]])>

In [22]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled,seed=42) # Operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

## Other way to make tensors

In [23]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [24]:
# Create a tensor of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Difference:
> Main difference between numpy array and tensor is that tensor can run on a GPU (Much Faster)

In [25]:
# Turn Numpy array into tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) #(1-24)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [26]:
A = tf.constant(numpy_A,shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

## Getting Information from tensors

* Shpae
* Rank
* Axis
* Size

In [27]:
# Create a Rank 4 tensor (4 Dimensions)

rank_4_tensor = tf.zeros(shape=(2,3,4)) # total elements = 2 * 3 * 4 = 24 elements
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [28]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [29]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=24>)

## Indexing tensors

In [30]:
rank_4_tensor[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)>

In [31]:
rank_4_tensor[:2,:1,:1]

<tf.Tensor: shape=(2, 1, 1), dtype=float32, numpy=
array([[[0.]],

       [[0.]]], dtype=float32)>

In [32]:
rank_2_tensor = tf.constant([[10,7],
                            [4,5]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  5]])>

In [33]:
# Adding extra dimenstion

rank_3_tensor = rank_2_tensor[...,tf.newaxis] #[:,:,tf.newaxis] sames
rank_3_tensor 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 4],
        [ 5]]])>

In [35]:
# Alternative
tf.expand_dims(rank_2_tensor,axis=-1)


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 4],
        [ 5]]])>

In [36]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 4,  5]]])>

## Tensor Operation

** Basic Operation
`+`,`-`,`*`,`/`

In [37]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [38]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [39]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [40]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [42]:
# Tensorflow built in function
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

## Matrix Multipication

* Dot Product
* Element wise product

In [43]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [61]:
x = tf.constant([[1,2],
                [3,4],
                [5,6]])

y = tf.constant([[7,8],
                [9,10],
                [11,12]])

In [62]:
tf.matmul(x,y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [63]:
# Let's change the shape of y
tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [64]:
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [65]:
# Using transpose
x,tf.transpose(x)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>)

In [66]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [67]:
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [68]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [70]:
tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

## Changing the datatype of tensor


In [71]:
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [72]:
C = tf.constant([7,9])
C.dtype

tf.int32

In [74]:
# float32 to float16
D = tf.cast(B, dtype=tf.float16)
D.dtype

tf.float16

In [75]:
# int32 to float32
E = tf.cast(C,dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([7., 9.], dtype=float32)>

## Aggegating tensor

In [76]:
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [77]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [78]:
# Create a random tensor
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([ 0, 45,  0, 38, 38, 33, 33, 87, 95, 45, 47,  6, 26, 40, 27, 21, 96,
       97, 42, 61, 51, 62, 85, 44, 60, 17, 75, 97, 10, 94, 40, 43, 61, 95,
       90, 40, 78,  8, 70, 28, 81, 19, 73, 96, 64, 12, 78, 46, 30, 67])>

In [79]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [80]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [81]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=97>

In [82]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=51>

In [83]:
# Fint the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2591>

In [93]:
import tensorflow_probability as tfp

tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int32, numpy=835>

In [95]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.890614>

In [98]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=834.6676>

## Find the positional minimum and maximum

In [101]:
tf.random.set_seed(42)
F =tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [103]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [105]:
# Positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [108]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [109]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [110]:
F[16]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## Squeezing a tensor (removing all single dimention)

In [114]:
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
           0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
           0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
           0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
           0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
           0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
           0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
           0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
           0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
           0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062]]]]],
      dtype=float32)>

In [115]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [116]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape

TensorShape([50])

## One-Hot encoding

In [117]:
some_list = [0,1,2,3,4]

tf.one_hot(some_list,depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [118]:
# Custome values for one-hot encoding
tf.one_hot(some_list,depth=5,on_value="YES",off_value="NO")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'YES', b'NO', b'NO', b'NO', b'NO'],
       [b'NO', b'YES', b'NO', b'NO', b'NO'],
       [b'NO', b'NO', b'YES', b'NO', b'NO'],
       [b'NO', b'NO', b'NO', b'YES', b'NO'],
       [b'NO', b'NO', b'NO', b'NO', b'YES']], dtype=object)>

## Squaring, log,square root

In [119]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [120]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [124]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [127]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and NumPy

In [129]:
J = tf.constant(np.array([1,2,3]))
J

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [130]:
np.array(J),type(np.array(J))

(array([1, 2, 3]), numpy.ndarray)